language: java
jdk:
  - openjdk8
branches:
  only:
    - master
# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ygygood@naver.com

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

deploy:
  provider: script
  script: "mvn -B -V deploy"
  skip_cleanup: true
